### ISSUE TITLE
运行程序的时候出现问题

### ISSUE THREAD

**Issue by tanxingeo** [waylife/RentCrawer#1]
![image](https://cloud.githubusercontent.com/assets/3351248/11760876/1d65c240-a0e8-11e5-88de-5f5c2081b930.png)

目前在检查不知道是init的问题，还是哪的问题。
ps：init文件没有修改过

**Comment by waylife** [comment]
python几？

**Comment by tanxingeo** [comment]
2.7.8

**Comment by tanxingeo** [comment]
是不是[]，这个符号有问题？

**Comment by waylife** [comment]
配置文件是怎么样的呢？
方便发上来看下么？

**Comment by tanxingeo** [comment]
[common]
key_search_word_list = 回龙观,西三旗
custom_black_list = 隔断,一室
start_time = 2015-09-01

[db]
db_file_name = rentdata.db3
result_file_name = rentdata_result.html

[newsmth]
newsmth_enable = True

[douban]
douban_enable = True
douban_cookie =
;second
douban_sleep_time = 1

[thread]
total_thread = 2

基本上没有改

**Comment by waylife** [comment]
应该是配置文件路径问题，Windows上可能适配有问题
ConfigParser第10行改成以下试试
self.cf.read(os.path.join(os.getcwd(),'config_file_name'))

http://stackoverflow.com/questions/16601757/python-configparser-nosectionerror-no-section-testinformation

**Comment by tanxingeo** [comment]
有点奇怪，stackoverflow这个解决办法也看了的，程序读的到.ini文件，应该在切分字符的时候出现问题。修改os.path.join没有结局问题

**Comment by waylife** [comment]
如果不着急，可以稍微等一段时间。

**Comment by mzlogin** [comment]
@waylife @tanxingeo 

我在 Mac 和 Win7 下可复现此问题，是配置文件路径的问题。

比如

```
mazhuang% pwd
/Users/mazhuang/github
mazhuang% python /Users/mazhuang/github/RentCrawer/RentCrawler/RentCrawler.py 
```

那指定配置文件时只指定 config.ini 那会去 `/Users/mazhuang/github/` 下找而不是去 `/Users/mazhuang/github/RentCrawer/RentCrawler/` 下找。

`os.getcwd()` 获取的也是当前工作路径，比如我上面的使用情况获取到的仍是 `/Users/mazhuang/github/`。

我改了一下，获取到当前 RentCrawler.py 文件所在文件夹，然后使用该文件夹下的 config.ini，修改见 #2

**Comment by waylife** [comment]
good @mzlogin thx~
