### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iaMeteor** [waylife/RentCrawer#5]
这个错误应该如何解决呢？
Error: Header value <RequestsCookieJar[<Cookie bid=otm0hlpGhlg for .douban.com/>]> must be of type str or bytes, not <class 'requests.cookies.RequestsCookieJar'>

谢谢

**Comment by waylife** [comment]
requests版本是？
请使用 sudo pip install requests -U 更新requests到最新版

**Comment by waylife** [comment]
可见issue6. requestes版本问题
