### ISSUE TITLE
关于Python租房爬虫的一个小问题

### ISSUE THREAD

**Issue by DannyChan129** [waylife/RentCrawer#6]
报错Error: Value for header {Cookie: <RequestsCookieJar[<Cookie bid=hcSgpj_cwjM for .douban.com/>]>} must be of type str or bytes, not <class 'requests.cookies.RequestsCookieJar'>
Search Finish,Please open result.html to view result
解决办法：安装 request 2.9.0 以下版本，就ok啦

**Comment by waylife** [comment]
好的，多谢反馈
